# Generated by Django 5.1.6 on 2025-02-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('overall_admin', 'Overall Admin'), ('sector_admin', 'Sector Admin'), ('service_provider', 'Service Provider'), ('client', 'Client')], db_index=True, default='client', max_length=20),
        ),
    ]
